language: scala

  jdk:
    - oraclejdk8

  script: sbt test

  addons:
    postgresql: "9.4"

  before_script:
    - psql -c "create database lunchman_test;" -U postgres
    - psql -c "create user lunchman_test with password 'test';" -U postgres
    - psql -c "grant all privileges on database lunchman_test to lunchman_test;" -U postgres
